[
    {
        "url": "https://api.github.com/repos/3b1b/manim/issues/1301",
        "repository_url": "https://api.github.com/repos/3b1b/manim",
        "labels_url": "https://api.github.com/repos/3b1b/manim/issues/1301/labels{/name}",
        "comments_url": "https://api.github.com/repos/3b1b/manim/issues/1301/comments",
        "events_url": "https://api.github.com/repos/3b1b/manim/issues/1301/events",
        "html_url": "https://github.com/3b1b/manim/pull/1301",
        "id": 777448506,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTQ3NzQ1Nzkx",
        "number": 1301,
        "title": "Some cleanups and bug fixes for the shaders branch",
        "user": {
            "login": "TonyCrane",
            "id": 44120331,
            "node_id": "MDQ6VXNlcjQ0MTIwMzMx",
            "avatar_url": "https://avatars.githubusercontent.com/u/44120331?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TonyCrane",
            "html_url": "https://github.com/TonyCrane",
            "followers_url": "https://api.github.com/users/TonyCrane/followers",
            "following_url": "https://api.github.com/users/TonyCrane/following{/other_user}",
            "gists_url": "https://api.github.com/users/TonyCrane/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TonyCrane/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TonyCrane/subscriptions",
            "organizations_url": "https://api.github.com/users/TonyCrane/orgs",
            "repos_url": "https://api.github.com/users/TonyCrane/repos",
            "events_url": "https://api.github.com/users/TonyCrane/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TonyCrane/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2021-01-02T11:52:21Z",
        "updated_at": "2021-01-15T14:55:14Z",
        "closed_at": "2021-01-02T17:43:11Z",
        "author_association": "COLLABORATOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/3b1b/manim/pulls/1301",
            "html_url": "https://github.com/3b1b/manim/pull/1301",
            "diff_url": "https://github.com/3b1b/manim/pull/1301.diff",
            "patch_url": "https://github.com/3b1b/manim/pull/1301.patch"
        },
        "body": "Here are some cleanups and bug fixes for the shaders branch\r\n\r\n- Deleted some unnecessary files and folders:\r\n   - The documents in `docs/` are for the master branch and are not currently being updated, so delete them in the shaders branch\r\n   - Travis related is mainly used to build documentation and publish python package, which are useless in shaders branch, delete\r\n   - The docker image is for the master branch, not for the shaders branch, so delete\r\n- Deleted the version of the package in `requirements.txt` for easy installation, and updated the `environment.yml` for anaconda\r\n- Fixed the `TypeError` caused by float number when determining the window position\r\n- Fixed the code that may cause `(xe)Latex error converting to dvi(xdv)`, same as #689 #1187\r\n- Fixed the bug in `extract_scene.py`, otherwise will cause the error of `TypeError: run() missing 1 required positional argument:'self'`after selecting the scene number\r\n- Updated `README.md`\r\n\r\n\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/3b1b/manim/issues/1315",
        "repository_url": "https://api.github.com/repos/3b1b/manim",
        "labels_url": "https://api.github.com/repos/3b1b/manim/issues/1315/labels{/name}",
        "comments_url": "https://api.github.com/repos/3b1b/manim/issues/1315/comments",
        "events_url": "https://api.github.com/repos/3b1b/manim/issues/1315/events",
        "html_url": "https://github.com/3b1b/manim/pull/1315",
        "id": 786902128,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTU1NzA0NzYx",
        "number": 1315,
        "title": "Fix some bugs of the shaders branch",
        "user": {
            "login": "TonyCrane",
            "id": 44120331,
            "node_id": "MDQ6VXNlcjQ0MTIwMzMx",
            "avatar_url": "https://avatars.githubusercontent.com/u/44120331?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TonyCrane",
            "html_url": "https://github.com/TonyCrane",
            "followers_url": "https://api.github.com/users/TonyCrane/followers",
            "following_url": "https://api.github.com/users/TonyCrane/following{/other_user}",
            "gists_url": "https://api.github.com/users/TonyCrane/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TonyCrane/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TonyCrane/subscriptions",
            "organizations_url": "https://api.github.com/users/TonyCrane/orgs",
            "repos_url": "https://api.github.com/users/TonyCrane/repos",
            "events_url": "https://api.github.com/users/TonyCrane/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TonyCrane/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 4,
        "created_at": "2021-01-15T13:37:48Z",
        "updated_at": "2021-01-16T01:28:37Z",
        "closed_at": "2021-01-15T19:13:34Z",
        "author_association": "COLLABORATOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/3b1b/manim/pulls/1315",
            "html_url": "https://github.com/3b1b/manim/pull/1315",
            "diff_url": "https://github.com/3b1b/manim/pull/1315.diff",
            "patch_url": "https://github.com/3b1b/manim/pull/1315.patch"
        },
        "body": "Here are some bug fixes for the shaders branch.\r\n\r\n- The first commit https://github.com/3b1b/manim/commit/79b81363309d4b9eb1a125d6dac75ee5cd674bc1 : I'm trying to make the `Text` class work perfectly in shaders. But I found that if I remove some of the changes in #1030(or #1031), the `Text` will directly work fine. So I revert them.\r\n- The second commit https://github.com/3b1b/manim/commit/78848b971cd3f7db0831db58ad4e9c40d1cf61e4 : I checked the docs of `logging` in the official python documentation and also checked the source code. I found that `logging.log` cannot receive the `file` argument, so I deleted this line, otherwise the following error will appear:\r\n```python\r\n  File \".../manimlib/extract_scene.py\", line 82, in get_scenes_to_render\r\n    file=sys.stderr\r\n  File \".../Anaconda3/envs/manim/lib/logging/__init__.py\", line 2014, in log\r\n    root.log(level, msg, *args, **kwargs)\r\n  File \".../Anaconda3/envs/manim/lib/logging/__init__.py\", line 1449, in log\r\n    self._log(level, msg, args, **kwargs)\r\nTypeError: _log() got an unexpected keyword argument 'file'\r\n```\r\n- The fourth commit https://github.com/3b1b/manim/commit/f696ba4100d43e67a3ebd05c05b514086cf435b6 : I write a brief example for `Text` to introduce and test it.\r\n- The fifth commit https://github.com/3b1b/manim/pull/1315/commits/fa3cad18e0e4d55e727b09ff210a79befa612b19 : Added the missing `ipython` package mentioned in https://github.com/3b1b/manim/pull/1301#issuecomment-753643071, and updated the `environment.yml` for Anaconda.\r\n- The sixth commit https://github.com/3b1b/manim/pull/1315/commits/c6fcaa93bb9c4482815fd03b19de2a52951cf143 : Deleted the file `stream_starter.py`. Because it seems that stream related functions have been completely deleted, but this file remains.\r\n- The eighth commit https://github.com/3b1b/manim/pull/1315/commits/7c04edcced38eea1046b934aa853e8500c4b3af9 : Added `font_size` to `Text`, and synchronized to the same size effect as `TextMobject` :\r\n![VG))B17{8$14CRJGRMDD7`R](https://user-images.githubusercontent.com/44120331/104747306-526edd00-578b-11eb-9848-36b29483299e.png)\r\n\r\n\r\n---\r\n@3b1b please have a look at these changes.\r\nBy the way, there is also a bug that I can't fix it, I talked in detail in #1314",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/3b1b/manim/issues/475",
        "repository_url": "https://api.github.com/repos/3b1b/manim",
        "labels_url": "https://api.github.com/repos/3b1b/manim/issues/475/labels{/name}",
        "comments_url": "https://api.github.com/repos/3b1b/manim/issues/475/comments",
        "events_url": "https://api.github.com/repos/3b1b/manim/issues/475/events",
        "html_url": "https://github.com/3b1b/manim/pull/475",
        "id": 421843466,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjYxNzk0NzAx",
        "number": 475,
        "title": "Fix bug for creating Matrix",
        "user": {
            "login": "niyiyu2316",
            "id": 36231703,
            "node_id": "MDQ6VXNlcjM2MjMxNzAz",
            "avatar_url": "https://avatars.githubusercontent.com/u/36231703?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/niyiyu2316",
            "html_url": "https://github.com/niyiyu2316",
            "followers_url": "https://api.github.com/users/niyiyu2316/followers",
            "following_url": "https://api.github.com/users/niyiyu2316/following{/other_user}",
            "gists_url": "https://api.github.com/users/niyiyu2316/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/niyiyu2316/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/niyiyu2316/subscriptions",
            "organizations_url": "https://api.github.com/users/niyiyu2316/orgs",
            "repos_url": "https://api.github.com/users/niyiyu2316/repos",
            "events_url": "https://api.github.com/users/niyiyu2316/events{/privacy}",
            "received_events_url": "https://api.github.com/users/niyiyu2316/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-03-16T19:24:31Z",
        "updated_at": "2019-04-04T15:54:23Z",
        "closed_at": "2019-04-04T15:54:23Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/3b1b/manim/pulls/475",
            "html_url": "https://github.com/3b1b/manim/pull/475",
            "diff_url": "https://github.com/3b1b/manim/pull/475.diff",
            "patch_url": "https://github.com/3b1b/manim/pull/475.patch"
        },
        "body": "Using python3.x,  and there is a problem creating Matrix(). \r\nError:\r\n`TypeError: descriptor 'strip' requires a 'str' object but received a 'numpy.int64'`\r\nAnd it can be solved by modify manimlib/mobject/svg/tex_mobject.py.\r\n\r\nI've tested it, and it seems that it works for now.\r\n\r\nBesides, just ignore the other four Commits...",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/3b1b/manim/issues/450",
        "repository_url": "https://api.github.com/repos/3b1b/manim",
        "labels_url": "https://api.github.com/repos/3b1b/manim/issues/450/labels{/name}",
        "comments_url": "https://api.github.com/repos/3b1b/manim/issues/450/comments",
        "events_url": "https://api.github.com/repos/3b1b/manim/issues/450/events",
        "html_url": "https://github.com/3b1b/manim/pull/450",
        "id": 412265232,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjU0NTE0OTY2",
        "number": 450,
        "title": "Fixed SVG parsing error with consecutive C or M coordinates.",
        "user": {
            "login": "ProgrammingIncluded",
            "id": 6433730,
            "node_id": "MDQ6VXNlcjY0MzM3MzA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6433730?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ProgrammingIncluded",
            "html_url": "https://github.com/ProgrammingIncluded",
            "followers_url": "https://api.github.com/users/ProgrammingIncluded/followers",
            "following_url": "https://api.github.com/users/ProgrammingIncluded/following{/other_user}",
            "gists_url": "https://api.github.com/users/ProgrammingIncluded/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ProgrammingIncluded/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ProgrammingIncluded/subscriptions",
            "organizations_url": "https://api.github.com/users/ProgrammingIncluded/orgs",
            "repos_url": "https://api.github.com/users/ProgrammingIncluded/repos",
            "events_url": "https://api.github.com/users/ProgrammingIncluded/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ProgrammingIncluded/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-02-20T06:26:32Z",
        "updated_at": "2019-02-20T06:30:52Z",
        "closed_at": "2019-02-20T06:29:44Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/3b1b/manim/pulls/450",
            "html_url": "https://github.com/3b1b/manim/pull/450",
            "diff_url": "https://github.com/3b1b/manim/pull/450.diff",
            "patch_url": "https://github.com/3b1b/manim/pull/450.patch"
        },
        "body": "## Problem\r\nCurrently the SVG parsing code found in svg_mobject.py does not include a few edge-cases from [W3 SVG 2.0](https://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands). The current condition of the code would not allow users to follow the repo recommended SVG tutorial by   [TalkingPhysics](https://talkingphysics.wordpress.com/2019/01/08/getting-started-animating-with-manim-and-python-3-7/).\r\n\r\nIn particular, edge cases outlined in the description for \"moveto\" and \"cubic Bezier curve\" commands.\r\n* \"M\" or \"m\" keywords can contain consecutive relative line-to coordinates after the initial moveto coordinates.\r\n* \"C\" or \"c\" keywords can contain consecutive control points for polybezier.\r\n\r\nThe case with \"C\" keywords had a corresponding snippet of code attempting to address this issue, however, a bug still occurred as an invalid amount of arguments is supplied to add_cubic_bezier_curve_to().\r\n\r\n## Fix\r\nThe solution for both are similar: after detecting more coordinates than the required number of coordinates for the keywords \"M\" and \"C\" respectfully, parse the extra coordinates and add them properly. Attention is given to whether the extra coordinates are relative or absolute.\r\n\r\n## Testing\r\nI ran two different before and after tests as well as ran an old project to make sure no major bugs have been introduced. Each SVG tested invokes a different error. Additional SVGs have been tested but not documented for the sake of readability.\r\n### Stick-Figure\r\nUsing the stickman SVG found in [TalkingPhysics' SVG tutorial](https://talkingphysics.wordpress.com/2018/08/14/working-with-svg-files-manim-series-part-12/). The stick-figure invoked errors for \"C\" case.\r\n\r\n#### Before\r\nThe following error occurred:\r\n> TypeError: add_cubic_bezier_curve_to() takes 4 positional arguments but 7 were given\r\n\r\n#### After\r\nWith blue color for entire figure:\r\n\r\n![Stick-Figure After](https://user-images.githubusercontent.com/6433730/53069937-7a1b7480-3492-11e9-98b2-5ec2fb57bd21.png)\r\n\r\n### Custom Logo\r\nWe created a custom logo to draw. Logo has been created in InkScape. These have been tested on both InkScape SVG, Optimized SVG, and Plain SVG. This logo invoked the errors for our \"M\" case.\r\n\r\n#### Before\r\n> TypeError: add_cubic_bezier_curve_to() takes 4 positional arguments but 6 were given\r\n\r\n#### After\r\n![Custom Logo After](https://user-images.githubusercontent.com/6433730/53070472-2ca00700-3494-11e9-9c14-9350271a3b96.png)\r\n\r\n### Pi Creature Test\r\nA random scene from previous old_projects was compiled that contained PiCreature. The file looked normal with PiCreature properly animated.\r\n\r\n![Random Scene Test](https://user-images.githubusercontent.com/6433730/53070655-bcde4c00-3494-11e9-9094-ccbd5b271301.png)\r\n\r\n## Final Remarks\r\nMore testing can be done by the maintainers from existing projects to make sure that no fatal bugs were introduced from the changes.\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/3b1b/manim/issues/1",
        "repository_url": "https://api.github.com/repos/3b1b/manim",
        "labels_url": "https://api.github.com/repos/3b1b/manim/issues/1/labels{/name}",
        "comments_url": "https://api.github.com/repos/3b1b/manim/issues/1/comments",
        "events_url": "https://api.github.com/repos/3b1b/manim/issues/1/events",
        "html_url": "https://github.com/3b1b/manim/pull/1",
        "id": 156889953,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NzE0OTEzNjY=",
        "number": 1,
        "title": "How to use",
        "user": {
            "login": "scottopell",
            "id": 996472,
            "node_id": "MDQ6VXNlcjk5NjQ3Mg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/996472?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/scottopell",
            "html_url": "https://github.com/scottopell",
            "followers_url": "https://api.github.com/users/scottopell/followers",
            "following_url": "https://api.github.com/users/scottopell/following{/other_user}",
            "gists_url": "https://api.github.com/users/scottopell/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/scottopell/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scottopell/subscriptions",
            "organizations_url": "https://api.github.com/users/scottopell/orgs",
            "repos_url": "https://api.github.com/users/scottopell/repos",
            "events_url": "https://api.github.com/users/scottopell/events{/privacy}",
            "received_events_url": "https://api.github.com/users/scottopell/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2016-05-26T02:22:13Z",
        "updated_at": "2016-05-26T14:38:41Z",
        "closed_at": "2016-05-26T03:31:03Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/3b1b/manim/pulls/1",
            "html_url": "https://github.com/3b1b/manim/pull/1",
            "diff_url": "https://github.com/3b1b/manim/pull/1.diff",
            "patch_url": "https://github.com/3b1b/manim/pull/1.patch"
        },
        "body": "I came across your youtube videos and wanted to figure out how to use this software because its awesome!\n\nI added a `requirements.txt` file with the dependencies that I could find (with notes about `aggdraw` in the readme) and switched the output dir to something within the folder. And added some basic setup notes in the readme.\n\nHowever I'm still getting the following error while trying to run `python extract_scene.py generate_logo.py`\n\n```\nTraceback (most recent call last):\n  File \"extract_scene.py\", line 205, in main\n    handle_scene(SceneClass(**scene_kwargs), **config)\n  File \"/Users/scott/scratch/manim/scene/scene.py\", line 32, in __init__\n    self.construct(*self.construct_args)\n  File \"/Users/scott/scratch/manim/./generate_logo.py\", line 50, in construct\n    self.interpolation_factor\nTypeError: interpolate() takes exactly 5 arguments (4 given)\n```\n\nThis seems to be an import error where its not finding the `helper.py` file in the root dir, but not sure why its happening exactly.\n\nHope this is a help to getting some usage notes up and I'm happy to help with that process if you'd like!\n",
        "performed_via_github_app": null,
        "score": 1.0
    }
]