[
    {
        "url": "https://api.github.com/repos/TheAlgorithms/Python/issues/998",
        "repository_url": "https://api.github.com/repos/TheAlgorithms/Python",
        "labels_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/998/labels{/name}",
        "comments_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/998/comments",
        "events_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/998/events",
        "html_url": "https://github.com/TheAlgorithms/Python/pull/998",
        "id": 466454413,
        "node_id": "MDExOlB1bGxSZXF1ZXN0Mjk2MjkxMDc5",
        "number": 998,
        "title": "Update average_median.py",
        "user": {
            "login": "SandersLin",
            "id": 45224617,
            "node_id": "MDQ6VXNlcjQ1MjI0NjE3",
            "avatar_url": "https://avatars.githubusercontent.com/u/45224617?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SandersLin",
            "html_url": "https://github.com/SandersLin",
            "followers_url": "https://api.github.com/users/SandersLin/followers",
            "following_url": "https://api.github.com/users/SandersLin/following{/other_user}",
            "gists_url": "https://api.github.com/users/SandersLin/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SandersLin/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SandersLin/subscriptions",
            "organizations_url": "https://api.github.com/users/SandersLin/orgs",
            "repos_url": "https://api.github.com/users/SandersLin/repos",
            "events_url": "https://api.github.com/users/SandersLin/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SandersLin/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-07-10T18:27:44Z",
        "updated_at": "2019-07-11T05:17:16Z",
        "closed_at": "2019-07-10T20:38:11Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/TheAlgorithms/Python/pulls/998",
            "html_url": "https://github.com/TheAlgorithms/Python/pull/998",
            "diff_url": "https://github.com/TheAlgorithms/Python/pull/998.diff",
            "patch_url": "https://github.com/TheAlgorithms/Python/pull/998.patch"
        },
        "body": "added doctest, fixed `TypeError: list indices must be integers or slices, not float` error due to` number/2` producing `float` type as index.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/TheAlgorithms/Python/issues/796",
        "repository_url": "https://api.github.com/repos/TheAlgorithms/Python",
        "labels_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/796/labels{/name}",
        "comments_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/796/comments",
        "events_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/796/events",
        "html_url": "https://github.com/TheAlgorithms/Python/pull/796",
        "id": 442683255,
        "node_id": "MDExOlB1bGxSZXF1ZXN0Mjc3NzQzMDA3",
        "number": 796,
        "title": "[FIX] maths/PrimeCheck",
        "user": {
            "login": "Julien00859",
            "id": 8208953,
            "node_id": "MDQ6VXNlcjgyMDg5NTM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8208953?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Julien00859",
            "html_url": "https://github.com/Julien00859",
            "followers_url": "https://api.github.com/users/Julien00859/followers",
            "following_url": "https://api.github.com/users/Julien00859/following{/other_user}",
            "gists_url": "https://api.github.com/users/Julien00859/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Julien00859/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Julien00859/subscriptions",
            "organizations_url": "https://api.github.com/users/Julien00859/orgs",
            "repos_url": "https://api.github.com/users/Julien00859/repos",
            "events_url": "https://api.github.com/users/Julien00859/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Julien00859/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-05-10T12:01:26Z",
        "updated_at": "2019-05-11T11:20:26Z",
        "closed_at": "2019-05-11T11:20:26Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/TheAlgorithms/Python/pulls/796",
            "html_url": "https://github.com/TheAlgorithms/Python/pull/796",
            "diff_url": "https://github.com/TheAlgorithms/Python/pull/796.diff",
            "patch_url": "https://github.com/TheAlgorithms/Python/pull/796.patch"
        },
        "body": "Current implementation is buggy and hard to read.\r\n\r\n* Negative values were raising a TypeError due to `math.sqrt`\r\n* 1 was considered prime, it is not.\r\n* 2 was considered not prime, it is.\r\n\r\nThe implementation has been corrected to fix the bugs and to enhance\r\nreadability.\r\n\r\nA docstring has been added with the definition of a prime number.\r\n\r\nA complete test suite has been written, it tests the 10 first primes, a\r\nnegative value, 0, 1 and some not prime numbers.\r\n\r\ncloses #795",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/TheAlgorithms/Python/issues/1095",
        "repository_url": "https://api.github.com/repos/TheAlgorithms/Python",
        "labels_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/1095/labels{/name}",
        "comments_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/1095/comments",
        "events_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/1095/events",
        "html_url": "https://github.com/TheAlgorithms/Python/pull/1095",
        "id": 476495249,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MzA0MDI5MzQ1",
        "number": 1095,
        "title": "Zeller's Congruence Algorithm",
        "user": {
            "login": "mrvnmchm",
            "id": 11682032,
            "node_id": "MDQ6VXNlcjExNjgyMDMy",
            "avatar_url": "https://avatars.githubusercontent.com/u/11682032?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mrvnmchm",
            "html_url": "https://github.com/mrvnmchm",
            "followers_url": "https://api.github.com/users/mrvnmchm/followers",
            "following_url": "https://api.github.com/users/mrvnmchm/following{/other_user}",
            "gists_url": "https://api.github.com/users/mrvnmchm/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mrvnmchm/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mrvnmchm/subscriptions",
            "organizations_url": "https://api.github.com/users/mrvnmchm/orgs",
            "repos_url": "https://api.github.com/users/mrvnmchm/repos",
            "events_url": "https://api.github.com/users/mrvnmchm/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mrvnmchm/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2019-08-03T22:33:42Z",
        "updated_at": "2019-08-05T03:22:29Z",
        "closed_at": "2019-08-05T03:22:29Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/TheAlgorithms/Python/pulls/1095",
            "html_url": "https://github.com/TheAlgorithms/Python/pull/1095",
            "diff_url": "https://github.com/TheAlgorithms/Python/pull/1095.diff",
            "patch_url": "https://github.com/TheAlgorithms/Python/pull/1095.patch"
        },
        "body": "Let me know of any other improvements I can make. :+1: \r\n\r\n```shell\r\nMarvins-MBP:maths marvinmichum$ python3 zellers_congruence.py --help\r\nusage: zellers_congruence.py [-h] date_input\r\n\r\nFind out what day of the week nearly any date is or was. Enter date as a\r\nstring in the mm-dd-yyyy or mm/dd/yyyy format\r\n\r\npositional arguments:\r\n  date_input  Date as a string (mm-dd-yyyy or mm/dd/yyyy)\r\n\r\noptional arguments:\r\n  -h, --help  show this help message and exit\r\n```\r\n\r\n```python\r\n>>> import ZellersCongruence as z\r\n>>> z.zeller('10/10/2018')\r\nYour date 10/10/2018, is a Wednesday!\r\n>>> z.zeller('04-23-1991')\r\nYour date 04-23-1991, is a Tuesday!\r\n>>> z.zeller('01-31-1976')\r\nYour date 01-31-1976, is a Saturday!\r\n```\r\n\r\n```shell\r\nMarvins-MBP:maths marvinmichum$ python3 zellers_congruence.py -v\r\nTrying:\r\n    zeller('01-31-2010')\r\nExpecting:\r\n    Your date 01-31-2010, is a Sunday!\r\nok\r\nTrying:\r\n    zeller('13-31-2010')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n    ...\r\n    ValueError: Month must be between 1 - 12\r\nok\r\nTrying:\r\n    zeller('.2-31-2010')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n    ...\r\n    ValueError: invalid literal for int() with base 10: '.2'\r\nok\r\nTrying:\r\n    zeller('01-33-2010')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n        ...\r\n    ValueError: Date must be between 1 - 31\r\nok\r\nTrying:\r\n    zeller('01-.4-2010')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n        ...\r\n    ValueError: invalid literal for int() with base 10: '.4'\r\nok\r\nTrying:\r\n    zeller('01-31*2010')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n        ...\r\n    ValueError: Date seperator must be '-' or '/'\r\nok\r\nTrying:\r\n    zeller('01^31-2010')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n        ...\r\n    ValueError: Date seperator must be '-' or '/'\r\nok\r\nTrying:\r\n    zeller('01-31-8999')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n        ...\r\n    ValueError: Year out of range. There has to be some sort of limit...right?\r\nok\r\nTrying:\r\n    zeller()\r\nExpecting:\r\n    Traceback (most recent call last):\r\n        ...\r\n    TypeError: zeller() missing 1 required positional argument: 'date_input'\r\nok\r\nTrying:\r\n    zeller('')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n        ...\r\n    ValueError: Must be 10 characters long\r\nok\r\nTrying:\r\n    zeller('01-31-19082939')\r\nExpecting:\r\n    Traceback (most recent call last):\r\n        ...\r\n    ValueError: Must be 10 characters long\r\nok\r\n1 items had no tests:\r\n    __main__\r\n1 items passed all tests:\r\n  11 tests in __main__.zeller\r\n11 tests in 2 items.\r\n11 passed and 0 failed.\r\nTest passed.\r\n```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/TheAlgorithms/Python/issues/600",
        "repository_url": "https://api.github.com/repos/TheAlgorithms/Python",
        "labels_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/600/labels{/name}",
        "comments_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/600/comments",
        "events_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/600/events",
        "html_url": "https://github.com/TheAlgorithms/Python/pull/600",
        "id": 378059442,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjI4ODU1MjMy",
        "number": 600,
        "title": "fix division by float issue in range heap.py",
        "user": {
            "login": "0xYasser",
            "id": 4710104,
            "node_id": "MDQ6VXNlcjQ3MTAxMDQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4710104?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/0xYasser",
            "html_url": "https://github.com/0xYasser",
            "followers_url": "https://api.github.com/users/0xYasser/followers",
            "following_url": "https://api.github.com/users/0xYasser/following{/other_user}",
            "gists_url": "https://api.github.com/users/0xYasser/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/0xYasser/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/0xYasser/subscriptions",
            "organizations_url": "https://api.github.com/users/0xYasser/orgs",
            "repos_url": "https://api.github.com/users/0xYasser/repos",
            "events_url": "https://api.github.com/users/0xYasser/events{/privacy}",
            "received_events_url": "https://api.github.com/users/0xYasser/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2018-11-06T22:23:47Z",
        "updated_at": "2018-11-10T18:05:27Z",
        "closed_at": "2018-11-10T18:05:27Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/TheAlgorithms/Python/pulls/600",
            "html_url": "https://github.com/TheAlgorithms/Python/pull/600",
            "diff_url": "https://github.com/TheAlgorithms/Python/pull/600.diff",
            "patch_url": "https://github.com/TheAlgorithms/Python/pull/600.patch"
        },
        "body": "Fix for dividing by float:\r\npython3 error: TypeError: 'float' object cannot be interpreted as an integer \r\npython2 error: TypeError: range() integer start argument expected, got float.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/TheAlgorithms/Python/issues/359",
        "repository_url": "https://api.github.com/repos/TheAlgorithms/Python",
        "labels_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/359/labels{/name}",
        "comments_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/359/comments",
        "events_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/359/events",
        "html_url": "https://github.com/TheAlgorithms/Python/pull/359",
        "id": 365189203,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjE5MTgyOTIx",
        "number": 359,
        "title": "Fixed error on chr function when decrypt",
        "user": {
            "login": "jonathangomz",
            "id": 24325747,
            "node_id": "MDQ6VXNlcjI0MzI1NzQ3",
            "avatar_url": "https://avatars.githubusercontent.com/u/24325747?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jonathangomz",
            "html_url": "https://github.com/jonathangomz",
            "followers_url": "https://api.github.com/users/jonathangomz/followers",
            "following_url": "https://api.github.com/users/jonathangomz/following{/other_user}",
            "gists_url": "https://api.github.com/users/jonathangomz/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jonathangomz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jonathangomz/subscriptions",
            "organizations_url": "https://api.github.com/users/jonathangomz/orgs",
            "repos_url": "https://api.github.com/users/jonathangomz/repos",
            "events_url": "https://api.github.com/users/jonathangomz/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jonathangomz/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2018-09-30T03:49:23Z",
        "updated_at": "2018-10-19T13:42:20Z",
        "closed_at": "2018-10-19T13:42:20Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/TheAlgorithms/Python/pulls/359",
            "html_url": "https://github.com/TheAlgorithms/Python/pull/359",
            "diff_url": "https://github.com/TheAlgorithms/Python/pull/359.diff",
            "patch_url": "https://github.com/TheAlgorithms/Python/pull/359.patch"
        },
        "body": "On line 23 when make the operations returns a float and chr function doesn't permit float values as parameters.\r\n\r\nAt least it throw this error on Python 3.6.5:\r\n_**TypeError: integer argument expected, got float**_\r\n\r\nFixed by adding int function to convert the result to integer.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/TheAlgorithms/Python/issues/283",
        "repository_url": "https://api.github.com/repos/TheAlgorithms/Python",
        "labels_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/283/labels{/name}",
        "comments_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/283/comments",
        "events_url": "https://api.github.com/repos/TheAlgorithms/Python/issues/283/events",
        "html_url": "https://github.com/TheAlgorithms/Python/pull/283",
        "id": 313947314,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTgxMzcwMzE1",
        "number": 283,
        "title": "fix type error (except an int) in jumpmp_search line 7.",
        "user": {
            "login": "clobob",
            "id": 10508051,
            "node_id": "MDQ6VXNlcjEwNTA4MDUx",
            "avatar_url": "https://avatars.githubusercontent.com/u/10508051?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/clobob",
            "html_url": "https://github.com/clobob",
            "followers_url": "https://api.github.com/users/clobob/followers",
            "following_url": "https://api.github.com/users/clobob/following{/other_user}",
            "gists_url": "https://api.github.com/users/clobob/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/clobob/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/clobob/subscriptions",
            "organizations_url": "https://api.github.com/users/clobob/orgs",
            "repos_url": "https://api.github.com/users/clobob/repos",
            "events_url": "https://api.github.com/users/clobob/events{/privacy}",
            "received_events_url": "https://api.github.com/users/clobob/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2018-04-13T02:19:50Z",
        "updated_at": "2018-04-13T13:36:37Z",
        "closed_at": "2018-04-13T13:36:37Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/TheAlgorithms/Python/pulls/283",
            "html_url": "https://github.com/TheAlgorithms/Python/pull/283",
            "diff_url": "https://github.com/TheAlgorithms/Python/pull/283.diff",
            "patch_url": "https://github.com/TheAlgorithms/Python/pull/283.patch"
        },
        "body": "Try to run this on Python 2.7.10.\r\nAn error occurs, the error log like this:\r\n_Traceback (most recent call last):\r\n  File \"jump_search.py\", line 25, in <module>\r\n    index = jump_search(arr, x)\r\n  File \"jump_search.py\", line 7, in jump_search\r\n    while arr[min(step, n)-1] < x:\r\nTypeError: list indices must be integers, not float_\r\n\r\nthe fix make the code can be run under python2 & python3.",
        "performed_via_github_app": null,
        "score": 1.0
    }
]