[
    {
        "url": "https://api.github.com/repos/tornadoweb/tornado/issues/2811",
        "repository_url": "https://api.github.com/repos/tornadoweb/tornado",
        "labels_url": "https://api.github.com/repos/tornadoweb/tornado/issues/2811/labels{/name}",
        "comments_url": "https://api.github.com/repos/tornadoweb/tornado/issues/2811/comments",
        "events_url": "https://api.github.com/repos/tornadoweb/tornado/issues/2811/events",
        "html_url": "https://github.com/tornadoweb/tornado/pull/2811",
        "id": 565308768,
        "node_id": "MDExOlB1bGxSZXF1ZXN0Mzc1MzczOTU1",
        "number": 2811,
        "title": "Fix Google OAuth example",
        "user": {
            "login": "bn0ir",
            "id": 2196548,
            "node_id": "MDQ6VXNlcjIxOTY1NDg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2196548?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bn0ir",
            "html_url": "https://github.com/bn0ir",
            "followers_url": "https://api.github.com/users/bn0ir/followers",
            "following_url": "https://api.github.com/users/bn0ir/following{/other_user}",
            "gists_url": "https://api.github.com/users/bn0ir/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bn0ir/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bn0ir/subscriptions",
            "organizations_url": "https://api.github.com/users/bn0ir/orgs",
            "repos_url": "https://api.github.com/users/bn0ir/repos",
            "events_url": "https://api.github.com/users/bn0ir/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bn0ir/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 114338333,
                "node_id": "MDU6TGFiZWwxMTQzMzgzMzM=",
                "url": "https://api.github.com/repos/tornadoweb/tornado/labels/auth",
                "name": "auth",
                "color": "0052cc",
                "default": false,
                "description": null
            },
            {
                "id": 209645437,
                "node_id": "MDU6TGFiZWwyMDk2NDU0Mzc=",
                "url": "https://api.github.com/repos/tornadoweb/tornado/labels/docs",
                "name": "docs",
                "color": "fbca04",
                "default": false,
                "description": null
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2020-02-14T12:51:24Z",
        "updated_at": "2020-06-20T17:02:35Z",
        "closed_at": "2020-06-20T17:02:34Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tornadoweb/tornado/pulls/2811",
            "html_url": "https://github.com/tornadoweb/tornado/pull/2811",
            "diff_url": "https://github.com/tornadoweb/tornado/pull/2811.diff",
            "patch_url": "https://github.com/tornadoweb/tornado/pull/2811.patch"
        },
        "body": "From tornado 6.0 OAuth2Mixin->authorize_redirect is an ordinary synchronous function.\r\nExample returns error when await is used:\r\n```Uncaught exception GET /auth/google (127.0.0.1)\r\n    HTTPServerRequest(protocol='http', host='example.com', method='GET', uri='/auth/google', version='HTTP/1.0', remote_ip='127.0.0.1')\r\n    Traceback (most recent call last):\r\n      File \"/usr/local/lib/python3.6/dist-packages/tornado/web.py\", line 1699, in _execute\r\n        result = await result\r\n      File \"app.py\", line 84, in get\r\n        extra_params = {\"approval_prompt\": \"auto\"}\r\n    TypeError: object NoneType can't be used in 'await' expression\r\n```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tornadoweb/tornado/issues/2137",
        "repository_url": "https://api.github.com/repos/tornadoweb/tornado",
        "labels_url": "https://api.github.com/repos/tornadoweb/tornado/issues/2137/labels{/name}",
        "comments_url": "https://api.github.com/repos/tornadoweb/tornado/issues/2137/comments",
        "events_url": "https://api.github.com/repos/tornadoweb/tornado/issues/2137/events",
        "html_url": "https://github.com/tornadoweb/tornado/pull/2137",
        "id": 251418051,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTM2NjAzMzIw",
        "number": 2137,
        "title": "Correctly clear and create a new ioloop during autoreload",
        "user": {
            "login": "jrdh",
            "id": 4718259,
            "node_id": "MDQ6VXNlcjQ3MTgyNTk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4718259?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jrdh",
            "html_url": "https://github.com/jrdh",
            "followers_url": "https://api.github.com/users/jrdh/followers",
            "following_url": "https://api.github.com/users/jrdh/following{/other_user}",
            "gists_url": "https://api.github.com/users/jrdh/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jrdh/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jrdh/subscriptions",
            "organizations_url": "https://api.github.com/users/jrdh/orgs",
            "repos_url": "https://api.github.com/users/jrdh/repos",
            "events_url": "https://api.github.com/users/jrdh/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jrdh/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2017-08-19T11:05:05Z",
        "updated_at": "2017-09-03T17:48:55Z",
        "closed_at": "2017-09-03T17:48:55Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tornadoweb/tornado/pulls/2137",
            "html_url": "https://github.com/tornadoweb/tornado/pull/2137",
            "diff_url": "https://github.com/tornadoweb/tornado/pull/2137.diff",
            "patch_url": "https://github.com/tornadoweb/tornado/pull/2137.patch"
        },
        "body": "After the removal of the deprecated `io_loop` arguments from all functions, the autoreload module stopped working as the wait function's usage was missed in the refactor. This resulted in the start function receiving an `IOLoop` object as its only argument which it then used as the `check_time` argument resulting in errors further down the line when the `check_time` is expected to be an int. This PR fixes that problem allowing the autoreload script to work correctly.\r\n\r\nTo the see the original bug just run the autoreload module, for example: `python -m tornado.autoreload -m tornado.test`, modify a test file after the first run completes and you'll get something like this:\r\n\r\n```\r\n[I 170819 12:02:37 testing:679] PASS\r\n[I 170819 12:02:37 autoreload:306] Script exited with status False\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"/usr/local/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/home/rogan/code/tornado/tornado/autoreload.py\", line 340, in <module>\r\n    main()\r\n  File \"/home/rogan/code/tornado/tornado/autoreload.py\", line 334, in main\r\n    wait()\r\n  File \"/home/rogan/code/tornado/tornado/autoreload.py\", line 139, in wait\r\n    start(io_loop)\r\n  File \"/home/rogan/code/tornado/tornado/autoreload.py\", line 127, in start\r\n    scheduler = ioloop.PeriodicCallback(callback, check_time)\r\n  File \"/home/rogan/code/tornado/tornado/ioloop.py\", line 1053, in __init__\r\n    if callback_time <= 0:\r\nTypeError: '<=' not supported between instances of 'AsyncIOLoop' and 'int'\r\n```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tornadoweb/tornado/issues/1889",
        "repository_url": "https://api.github.com/repos/tornadoweb/tornado",
        "labels_url": "https://api.github.com/repos/tornadoweb/tornado/issues/1889/labels{/name}",
        "comments_url": "https://api.github.com/repos/tornadoweb/tornado/issues/1889/comments",
        "events_url": "https://api.github.com/repos/tornadoweb/tornado/issues/1889/events",
        "html_url": "https://github.com/tornadoweb/tornado/pull/1889",
        "id": 189343299,
        "node_id": "MDExOlB1bGxSZXF1ZXN0OTM3MzA4ODA=",
        "number": 1889,
        "title": "Avoid spurious warnings at shutdown",
        "user": {
            "login": "pitrou",
            "id": 1721820,
            "node_id": "MDQ6VXNlcjE3MjE4MjA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1721820?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pitrou",
            "html_url": "https://github.com/pitrou",
            "followers_url": "https://api.github.com/users/pitrou/followers",
            "following_url": "https://api.github.com/users/pitrou/following{/other_user}",
            "gists_url": "https://api.github.com/users/pitrou/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pitrou/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pitrou/subscriptions",
            "organizations_url": "https://api.github.com/users/pitrou/orgs",
            "repos_url": "https://api.github.com/users/pitrou/repos",
            "events_url": "https://api.github.com/users/pitrou/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pitrou/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2016-11-15T09:42:08Z",
        "updated_at": "2016-11-20T13:51:19Z",
        "closed_at": "2016-11-20T13:51:19Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tornadoweb/tornado/pulls/1889",
            "html_url": "https://github.com/tornadoweb/tornado/pull/1889",
            "diff_url": "https://github.com/tornadoweb/tornado/pull/1889.diff",
            "patch_url": "https://github.com/tornadoweb/tornado/pull/1889.patch"
        },
        "body": "When there are still active coroutines at interpreter shutdown, you can see sometimes warnings such as:\r\n```\r\nException ignored in: <bound method Future.__del__ of <tornado.concurrent.Future object at 0x7f56a8b142e8>>\r\nTraceback (most recent call last):\r\n  File \"/home/antoine/tornado/tornado/concurrent.py\", line 338, in __del__\r\nTypeError: 'NoneType' object is not callable\r\n```\r\n\r\nThese are distracting and don't bear any useful information, so silence them.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tornadoweb/tornado/issues/1689",
        "repository_url": "https://api.github.com/repos/tornadoweb/tornado",
        "labels_url": "https://api.github.com/repos/tornadoweb/tornado/issues/1689/labels{/name}",
        "comments_url": "https://api.github.com/repos/tornadoweb/tornado/issues/1689/comments",
        "events_url": "https://api.github.com/repos/tornadoweb/tornado/issues/1689/events",
        "html_url": "https://github.com/tornadoweb/tornado/pull/1689",
        "id": 148014739,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjYyOTczMTQ=",
        "number": 1689,
        "title": "Avoid uncaught exception when _xsrf argument could not be decoded",
        "user": {
            "login": "harboecp",
            "id": 9168435,
            "node_id": "MDQ6VXNlcjkxNjg0MzU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9168435?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/harboecp",
            "html_url": "https://github.com/harboecp",
            "followers_url": "https://api.github.com/users/harboecp/followers",
            "following_url": "https://api.github.com/users/harboecp/following{/other_user}",
            "gists_url": "https://api.github.com/users/harboecp/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/harboecp/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/harboecp/subscriptions",
            "organizations_url": "https://api.github.com/users/harboecp/orgs",
            "repos_url": "https://api.github.com/users/harboecp/repos",
            "events_url": "https://api.github.com/users/harboecp/events{/privacy}",
            "received_events_url": "https://api.github.com/users/harboecp/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2016-04-13T10:19:51Z",
        "updated_at": "2016-04-24T18:39:10Z",
        "closed_at": "2016-04-24T18:39:10Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tornadoweb/tornado/pulls/1689",
            "html_url": "https://github.com/tornadoweb/tornado/pull/1689",
            "diff_url": "https://github.com/tornadoweb/tornado/pull/1689.diff",
            "patch_url": "https://github.com/tornadoweb/tornado/pull/1689.patch"
        },
        "body": "This is primarily to avoid the following error in `check_xsrf_cookie` when an user sends invalid cookies:\n\n> TypeError: a bytes-like object is required, not 'NoneType\n\nThis fixes the error handling of xsrf cookies last changed by https://github.com/tornadoweb/tornado/pull/1299\n",
        "performed_via_github_app": null,
        "score": 1.0
    }
]